spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: java12pass
    url: jdbc:postgresql://18.194.161.195:5432/postgres
    username: java12user

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #DATA-INIT
  sql:
    init:
      data-locations: classpath:datainit/dataInit.sql
      mode: never

  #Migration
  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true