spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: yiman
    url: jdbc:postgresql://localhost:5434/lms
    username: postgres
#    password: ${POSTGRES_PASSWORD}
#    url: ${POSTGRES_DB}
#    username: ${POSTGRES_USER}


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #DATA-INIT
  sql:
    init:
      data-locations: classpath:datainit/dataInit.sql
      mode: never

  #Migration
  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true