spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: yiman
    url: jdbc:postgresql://localhost:5434/lms
    username: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  #DATA-INIT
  sql:
    init:
      data-locations: classpath:datainit/dataInit.sql
      mode: never

  #Migration
  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true
