aws.s3:
  credentials:
    aws-access-key_id: ${AWS_ACCESS_KEY_ID}
    aws-access-secret-key: ${AWS_SECRET_ACCESS_KEY}
  bucket:
    name: ${AWS_BUCKET_NAME}
    profile-path: ${AWS_BUCKET_URL}
    region: ${AWS_DEFAULT_REGION}