spring:
    application:
        name: lms-b12
    mail:
        host: smtp.gmail.com
        port: 587
        username: nurkamilkamchiev@gmail.com
        password: akst vqxz graa hzfe
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
cloud:
    aws:
        credentials:
            access-key:
            secret-key:
        region:
            static:
        stack:
            auto: false

application:
    bucket:
        name: