spring:
    application:
        name: lms-b12
    mail:
        host: smtp.gmail.com
        port: 587
        username: nurkamilkamchiev@gmail.com
        password: akst vqxz graa hzfe
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
#    jpa:
#        defer-datasource-initialization: true
#    sql:
#        init:
#            data-locations: classpath:datainit/dataInit.sql
#            mode: always
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
cloud:
    aws:
        credentials:
            access-key:
            secret-key:
        region:
            static:
        stack:
            auto: false

application:
    bucket:
        name: