spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_DB}
    username: ${POSTGRES_USER}

  #Hibernate/JPA settings.
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #EMAIL
  application:
    name: lms-b12
  mail:
    host: smtp.gmail.com
    port: 587
    username: nurkamilkamchiev@gmail.com
    password: akst vqxz graa hzfe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #DATA-INIT
  sql:
    init:
      data-locations: classpath:datainit/dataInit.sql
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #Migration
  flyway:
    enabled: false
    locations: classpath:db.migration
    baseline-on-migrate: false

flyway:
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  url: ${POSTGRES_DB}


#S3 FILE
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      profile-path: ${AWS_BUCKET_URL}
    region:
      static: ${AWS_DEFAULT_REGION}

application:
  bucket:
    name: ${AWS_BUCKET_NAME}

#JWT
app:
  jwt:
    secret: learning-management-system-java-12

server:
  error:
    include-message: always

