spring:
  application:
    name: lms-b12
  config:
    import:
        - classpath:/settings/s3-settings.yml
        - classpath:/settings/mydb-settings.yml
        - classpath:/settings/mail-settings.yml
        - classpath:/settings/security-settings.yml
        - classpath:/settings/server-settings.yml
