spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: yiman
    url: jdbc:postgresql://localhost:5434/lms
    username: postgres

#Hibernate/JPA settings.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#EMAIL
  application:
    name: lms-b12
  mail:
    host: smtp.gmail.com
    port: 587
    username: nurkamilkamchiev@gmail.com
    password: akst vqxz graa hzfe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#DATA-INIT
  sql:
    init:
      data-locations: classpath:datainit/dataInit.sql
      mode: never
      continue-on-error: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#Migration
  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true
    user: postgres
    password: yiman
    url: jdbc:postgresql://localhost:5434/lms


#S3 FILE
cloud:
  aws:
    credentials:
      access-key: AKIA3KYNRCVIMLD7EX27
      secret-key: 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
      profile-path: https://lms-b12.s3.eu-central-1.amazonaws.com/
    region:
      static: eu-central-1
    stack:
      auto: false

application:
  bucket:
    name: lms-b12

#JWT
app:
  jwt:
    secret: learning-management-system-java-12

server:
  error:
    include-message: always

  port: 5445